baseURL = 'https://pawelwiejkut.dev/'
languageCode = 'en-us'
title = 'Pawel Wiejkut'
theme = "PaperMod"
sectionPagesMenu = "main"
googleAnalytics = 'G-3R9CLWGY39'

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
  identifier = 'search'
  name = 'Search'
  pre = "<i class='fa fa-heart'></i>"
  url = '/search/'
  weight = 5
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 10 
[[menu.main]]
  identifier = "abapodpodstaw"
  name = "ABAP od postaw 🇵🇱 "
  url = "/abapodpodstaw/"
  weight = 0
[[menu.main]]
  identifier = "mydevs"
  name = "My devs"
  url = "/mydevs/"
  weight = 0

[params]
env = "production"
comments = true
[params.assets]
favicon = "./profile.png"
favicon16x16 = "./profile.png"
favicon32x32 = "./profile.png"
apple_touch_icon = "./profile.png"
safari_pinned_tab = "./profile.png"

[params.homeInfoParams]
Title = "Hi there 👋"
Content = """ ![image alt >](/profile.png)
My name is Pawel Wiejkut and I'm a SAP Consultant since 2016.  
Here you can find some of my knowledge about SAP & Databases. For videos please check out my youtube channel and follow me on instagram.
This blog is migrated from wordpress version - pawelwiejkut.net.</br>**BW | ABAP | SAC | HANA**</br>


<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup form {display:block; position:left; text-align:left; 0 10px 3%}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://pawelwiejkut.us19.list-manage.com/subscribe/post?u=ead4e0dc04f1f8c07403a39ac&amp;id=500c9c1881" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ead4e0dc04f1f8c07403a39ac_500c9c1881" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe to newsletter" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
"""

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/subrc0"
[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/pawelwiejkut"
[[params.socialIcons]]
name = "github"
url = "https://github.com/pawelwiejkut"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/pawelwiejkut"
[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/user/PawelWiejkut/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]




