baseURL = 'https://pawelwiejkut.dev/'
languageCode = 'en-us'
title = 'Pawel Wiejkut'
theme = "PaperMod"
sectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
  identifier = 'search'
  name = 'Search'
  pre = "<i class='fa fa-heart'></i>"
  url = '/search/'
  weight = 100
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 10 
[[menu.main]]
  identifier = "abapodpodstaw"
  name = "ABAP od postaw 🇵🇱 "
  url = "/abapodpodstaw/"
  weight = 0

[params]
env = "production"
comments = true


[params.homeInfoParams]
Title = "Hi there 👋"
Content = """ ![image alt >](/me.jpeg)
My name is Pawel Wiejkut and I'm a SAP Consultant since 2016.  
Here you can find some of my knowledge about SAP & Databases. For videos please check out my Youtube Channel.
This blog is migrated from pawelwiejkut.net.
**BW | ABAP | SAC | HANA** """

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/subrc0"
[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/pawelwiejkut"
[[params.socialIcons]]
name = "github"
url = "https://github.com/pawelwiejkut"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/pawelwiejkut"
[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/user/PawelWiejkut/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[assets]
favicon = "favicon.png"
favicon16x16 = "favicon.png"
favicon32x32 = "favicon.png"


